# Generated by Django 4.1.3 on 2023-06-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjiviefy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
