# Generated by Django 4.1.3 on 2023-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjiviefy', '0002_podcast_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_futured',
            field=models.BooleanField(default=False),
        ),
    ]
