# Generated by Django 4.1.3 on 2023-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjiviefy', '0003_podcast_is_futured'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_record', models.FileField(upload_to='uploads/%y/%m/%d')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='is_futured',
            new_name='is_featured',
        ),
    ]
