# Generated by Django 4.1.3 on 2023-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjiviefy', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
